#!/usr/bin/env python3
"""
DIHCA2 Job Runner for parallel tclean imaging.
Adapted from the ACES job_runner.py to work with DIHCA2 data.

This script:
1. Reads the metadata JSON file generated by inspect_ms_metadata.py
2. Sets up SLURM jobs using the ACES parallel_tclean functionality
3. Manages job dependencies and cleanup
"""

import os
import sys
import json
import glob
import copy
import subprocess
import datetime
import argparse
from pathlib import Path

from aces.imaging.parallel_tclean import parallel_clean_slurm


class DIHCA2JobRunner:
    def __init__(self, metadata_file, tclean_commands_file,
                 workdir='/red/adamginsburg/dihca/workdir',
                 logdir='/red/adamginsburg/logs',
                 account='astronomy-dept',
                 qos='astronomy-dept-b',
                 casa_version='casa-6.4.3-2-pipeline-2021.3.0.17'):

        self.metadata_file = metadata_file
        self.tclean_commands_file = tclean_commands_file
        self.workdir = workdir
        self.logdir = logdir
        self.account = account
        self.qos = qos
        self.casa_version = casa_version

        # Create directories
        os.makedirs(workdir, exist_ok=True)
        os.makedirs(logdir, exist_ok=True)

        # Load metadata and commands
        self.load_data()

        # Default parameters for different types of observations
        self.default_parameters = {
            'mem': 128,  # GB
            'ntasks': 16,
            'nchan_per': 16,
            'mem_per_cpu': '8gb',
            'jobtime': '96:00:00'
        }

    def load_data(self):
        """Load metadata and tclean commands from JSON files."""
        print(f"Loading metadata from {self.metadata_file}")
        with open(self.metadata_file, 'r') as f:
            self.metadata = json.load(f)

        # check metadata for reasonable image sizes (temporarily disabled while updating metadata)
        for ms_name, ms_data in self.metadata.items():
            if 'suggested_imaging_params' in ms_data:
                imsize = ms_data['suggested_imaging_params'].get('suggested_imsize_pixels', 0)
                if imsize > 4096:
                    raise ValueError(f"Suggested imsize {imsize} is too large for {ms_name}")

        print(f"Loading tclean commands from {self.tclean_commands_file}")
        with open(self.tclean_commands_file, 'r') as f:
            self.tclean_commands = json.load(f)

        # Check tclean commands for reasonable image sizes
        for ms_name, ms_data in self.tclean_commands.items():
            if 'tclean_cube_pars' in ms_data:
                for spw_id, tclean_params in ms_data['tclean_cube_pars'].items():
                    if 'width' in tclean_params:
                        assert tclean_params['width'] == 1, f"Width {tclean_params['width']} is not 1 for {ms_name} spw{spw_id}"
                    if 'imsize' in tclean_params:
                        imsize = tclean_params['imsize']
                        if isinstance(imsize, list) and len(imsize) > 0:
                            max_imsize = max(imsize)
                            if max_imsize > 4096:
                                raise ValueError(f"Imsize {imsize} is too large for {ms_name} spw{spw_id}")

        print(f"Loaded {len(self.metadata)} MS files with {sum(len(ms['spectral_windows']) for ms in self.metadata.values())} total spectral windows")

    def get_running_jobs(self):
        """Get currently running/pending jobs from SLURM."""
        sacct = subprocess.check_output([
            '/opt/slurm/bin/sacct',
            '--format=JobID,JobName%45,Account%15,QOS%17,State,Priority%8,ReqMem%8,CPUTime%15,Elapsed%15,Timelimit%15,NodeList%20'
        ])

        # Parse the output to get job information
        lines = sacct.decode().split('\n')
        jobs = {}
        for line in lines[2:]:  # Skip header lines
            if line.strip():
                parts = line.split()
                if len(parts) >= 5:
                    job_id = parts[0]
                    job_name = parts[1]
                    state = parts[4]
                    jobs[job_name] = {'job_id': job_id, 'state': state}

        return jobs

    def check_completed_array_tasks(self, imagename, nchan, nchan_per, savedir):
        """Check which array tasks have completed successfully by examining output files."""
        completed_tasks = []
        total_tasks = nchan // nchan_per
        if nchan % nchan_per != 0:
            total_tasks += 1  # Account for partial last chunk

        for task_id in range(total_tasks):
            start = task_id * nchan_per
            # Expected output file name (matches parallel_tclean naming)
            expected_image = f"{imagename}.{start:04d}.{nchan_per:03d}.image"

            # Check both workdir and final savedir
            # The imagename already contains the field and spw info (e.g., "008.672-00.682_spw0")
            job_workdir = imagename  # This matches how job_workdir is created in run_parallel_imaging
            workdir_path = os.path.join(self.workdir, job_workdir, expected_image)
            savedir_path = os.path.join(savedir, expected_image) if savedir else None

            if os.path.exists(workdir_path) or (savedir_path and os.path.exists(savedir_path)):
                completed_tasks.append(task_id)

        return completed_tasks, total_tasks

    def should_skip_job(self, jobname, running_jobs, args, **job_params):
        """Determine if a job should be skipped based on its current status."""
        if jobname not in running_jobs:
            return False, "Job not found in queue", None

        state = running_jobs[jobname]['state']
        job_id = running_jobs[jobname]['job_id']

        if state == 'RUNNING':
            return True, f"Job {jobname} is RUNNING as {job_id}", None
        elif state == 'PENDING':
            return True, f"Job {jobname} is PENDING as {job_id}", None
        elif state == 'COMPLETED':
            if args.redo_completed:
                return False, f"Redoing COMPLETED job {jobname} ({job_id})", None
            else:
                return True, f"Job {jobname} is COMPLETED as {job_id}", None
        elif state == 'FAILED':
            if args.redo_failed:
                # Check which array tasks completed successfully
                if 'imagename' in job_params and 'nchan' in job_params and 'nchan_per' in job_params:
                    completed_tasks, total_tasks = self.check_completed_array_tasks(
                        job_params['imagename'],
                        job_params['nchan'],
                        job_params['nchan_per'],
                        job_params.get('savedir')
                    )

                    if len(completed_tasks) == total_tasks:
                        return True, f"Job {jobname} FAILED but all {total_tasks} array tasks completed successfully", None
                    elif len(completed_tasks) > 0:
                        # Some tasks completed - return list of tasks that need to be rerun
                        failed_tasks = [i for i in range(total_tasks) if i not in completed_tasks]
                        return False, f"Redoing FAILED job {jobname} ({job_id}) - {len(completed_tasks)}/{total_tasks} tasks completed", failed_tasks
                    else:
                        return False, f"Redoing FAILED job {jobname} ({job_id}) - no tasks completed", None
                else:
                    return False, f"Redoing FAILED job {jobname} ({job_id})", None
            else:
                return True, f"Job {jobname} is FAILED as {job_id}", None
        elif state == 'TIMEOUT':
            return False, f"Restarting TIMEOUT job {jobname} ({job_id})", None

        return False, f"Job {jobname} has state {state}", None

    def _run_selective_parallel_clean(self, parallel_params, failed_tasks):
        """Run parallel_clean_slurm with selective array tasks by modifying the SLURM command."""
        import tempfile
        import shutil

        # Remove the selective tasks parameter before calling parallel_clean_slurm
        selective_params = parallel_params.copy()
        if '_selective_tasks' in selective_params:
            del selective_params['_selective_tasks']

        # Create array specification for failed tasks
        if len(failed_tasks) == 1:
            array_spec = str(failed_tasks[0])
        else:
            # Convert list of task IDs to SLURM array format (e.g., "1,3,5-7,10")
            array_spec = self._format_slurm_array(failed_tasks)

        print(f"  Selective array tasks: {array_spec}")

        # We need to monkey-patch the parallel_clean_slurm function to use our custom array spec
        # This is a bit hacky but necessary since we can't modify the ACES code directly

        # Store original subprocess.check_output
        original_check_output = subprocess.check_output
        original_print = print

        def patched_check_output(cmd_list):
            # Modify the SLURM command to use our selective array specification
            if isinstance(cmd_list, list) and len(cmd_list) > 0 and 'sbatch' in cmd_list[0]:
                # Find and replace the --array parameter
                for i, arg in enumerate(cmd_list):
                    if arg.startswith('--array='):
                        cmd_list[i] = f'--array={array_spec}'
                        break
                print(f"Modified SLURM command for selective resubmission: {' '.join(cmd_list)}")

            return original_check_output(cmd_list)

        # Temporarily patch subprocess.check_output
        subprocess.check_output = patched_check_output

        try:
            # Call the original function with patched subprocess
            parallel_clean_slurm(**selective_params)
        finally:
            # Restore original function
            subprocess.check_output = original_check_output

    def _format_slurm_array(self, task_ids):
        """Format a list of task IDs into SLURM array specification (e.g., "1,3,5-7,10")."""
        if not task_ids:
            return ""

        task_ids = sorted(task_ids)
        ranges = []
        start = task_ids[0]
        end = start

        for i in range(1, len(task_ids)):
            if task_ids[i] == end + 1:
                end = task_ids[i]
            else:
                if start == end:
                    ranges.append(str(start))
                else:
                    ranges.append(f"{start}-{end}")
                start = end = task_ids[i]

        # Add the last range
        if start == end:
            ranges.append(str(start))
        else:
            ranges.append(f"{start}-{end}")

        return ",".join(ranges)

    def run_parallel_imaging(self, ms_name, spw_id, args):
        """Run parallel tclean imaging for a specific MS and spectral window."""

        # Get metadata and parameters
        ms_metadata = self.metadata[ms_name + '.ms']
        tclean_params = self.tclean_commands[ms_name]['tclean_cube_pars'][str(spw_id)]
        field_name = self.tclean_commands[ms_name]['field_name']

        # Create job name
        jobname = f"dihca2_{ms_name}_spw{spw_id}"

        print(f"Setting up parallel imaging job for {ms_name} spw{spw_id}")

        # Get spectral window info
        spw_info = ms_metadata['spectral_windows'][str(spw_id)]
        nchan = spw_info['nchan']

        # Create a copy of tclean parameters for modification
        tcpars = copy.deepcopy(tclean_params)

        # Update paths and parameters
        tcpars['vis'] = [ms_metadata['ms_path']]
        tcpars['field'] = field_name
        tcpars['spw'] = spw_id

        imsize = tcpars['imsize']
        if imsize[0] > 4096:
            raise ValueError(f"Imsize {imsize} is too large for {ms_name} spw{spw_id}")

        # Set up imaging parameters
        imagename = f"{field_name}_spw{spw_id}"

        # First check if all output products already exist (regardless of SLURM queue status)
        job_params = {
            'imagename': imagename,
            'nchan': nchan,
            'nchan_per': self.default_parameters['nchan_per'],
            'savedir': '/orange/adamginsburg/salt/dihca2imaging/final_products'
        }

        completed_tasks, total_tasks = self.check_completed_array_tasks(
            job_params['imagename'],
            job_params['nchan'],
            job_params['nchan_per'],
            job_params.get('savedir')
        )

        if len(completed_tasks) == total_tasks:
            print(f"Skipping {jobname}: All {total_tasks} array tasks already completed (output products exist)")
            return
        elif len(completed_tasks) > 0:
            print(f"Found {len(completed_tasks)}/{total_tasks} completed array tasks for {jobname}")

        # Check SLURM queue status and handle selective resubmission
        running_jobs = self.get_running_jobs()

        # Check if any merge jobs are running - if so, don't submit new jobs
        merge_jobs_running = [name for name in running_jobs.keys() if name.endswith('_merge') and running_jobs[name]['state'] == 'RUNNING']
        if merge_jobs_running:
            print(f"Skipping {jobname}: Merge job(s) currently running: {', '.join(merge_jobs_running)}")
            return

        should_skip, reason, failed_tasks = self.should_skip_job(jobname, running_jobs, args, **job_params)
        if should_skip:
            print(f"Skipping {jobname}: {reason}")
            return

        # If we have some completed tasks but job is not in queue, only submit missing tasks
        if len(completed_tasks) > 0 and jobname not in running_jobs:
            failed_tasks = [i for i in range(total_tasks) if i not in completed_tasks]
            print(f"Job {jobname} not in queue but {len(completed_tasks)}/{total_tasks} tasks completed")
            print(f"Will submit only missing array tasks: {failed_tasks}")

        # Create working directory for this job
        job_workdir = os.path.join(self.workdir, f"{ms_name}_spw{spw_id}")
        os.makedirs(job_workdir, exist_ok=True)

        # Parameters for parallel_clean_slurm
        parallel_params = {
            'nchan': nchan,
            'imagename': imagename,
            'spw': spw_id,
            'start': tcpars.get('start', 0),
            'width': tcpars.get('width', 1),
            'field': field_name,
            'jobname': jobname,
            'workdir': job_workdir,
            'logdir': self.logdir,
            'account': self.account,
            'qos': self.qos,
            'jobtime': self.default_parameters['jobtime'],
            'CASAVERSION': self.casa_version,
            'ntasks': self.default_parameters['ntasks'],
            'nchan_per': self.default_parameters['nchan_per'],
            'mem_per_cpu': self.default_parameters['mem_per_cpu'],
            'dry': args.dry_run,
            'savedir': '/orange/adamginsburg/salt/dihca2imaging/final_products',
            'remove_incomplete_psf': True,
            'remove_incomplete_weight': True,
            # only keep image - we're not saving model, etc.
            'suffixes_to_merge_and_export': ['image', 'image.pbcor', 'model']
        }

        # Remove parameters that parallel_clean_slurm doesn't expect
        for key in ['imagename', 'nchan', 'start', 'width', 'spw']:
            if key in tcpars:
                del tcpars[key]

        # Add remaining tclean parameters
        parallel_params.update(tcpars)

        # Handle selective array resubmission for failed tasks
        if failed_tasks is not None:
            print(f"Selective resubmission: running only tasks {failed_tasks}")
            # We'll modify the SLURM array specification after parallel_clean_slurm generates the command
            parallel_params['_selective_tasks'] = failed_tasks

        print(f"Launching parallel_clean_slurm with parameters:")
        for key, value in parallel_params.items():
            if key not in ['vis', '_selective_tasks']:  # Don't print long file paths or internal params
                print(f"  {key}: {value}")

        # Call parallel_clean_slurm (potentially with selective array tasks)
        if failed_tasks is not None and len(failed_tasks) > 0:
            self._run_selective_parallel_clean(parallel_params, failed_tasks)
        elif failed_tasks is not None and len(failed_tasks) == 0:
            print(f"No array tasks to submit for {jobname} - all tasks already completed")
            return
        else:
            parallel_clean_slurm(**parallel_params)
        print(f"Successfully launched job {jobname}")

    def run_all_jobs(self, args):
        """Run imaging jobs for all MS files and spectral windows."""

        # Check current job status before starting
        running_jobs = self.get_running_jobs()
        if running_jobs:
            print(f"\nCurrent SLURM queue status:")
            running_count = sum(1 for job in running_jobs.values() if job['state'] == 'RUNNING')
            pending_count = sum(1 for job in running_jobs.values() if job['state'] == 'PENDING')
            merge_running = [name for name in running_jobs.keys() if name.endswith('_merge') and running_jobs[name]['state'] == 'RUNNING']

            print(f"  RUNNING jobs: {running_count}")
            print(f"  PENDING jobs: {pending_count}")
            if merge_running:
                print(f"  RUNNING merge jobs: {', '.join(merge_running)}")
                print(f"  Note: No new jobs will be submitted while merge jobs are running")
            print()

        total_jobs = 0
        launched_jobs = 0
        max_jobs = getattr(args, 'max_jobs', None)

        for ms_name, ms_metadata in self.metadata.items():
            ms_key = ms_name.replace('.ms', '')

            if ms_key not in self.tclean_commands:
                print(f"Warning: No tclean commands found for {ms_name}")
                continue

            # Process each spectral window
            for spw_id_str in ms_metadata['spectral_windows'].keys():
                spw_id = int(spw_id_str)
                total_jobs += 1

                # Check if we've reached the maximum number of jobs
                if max_jobs is not None and launched_jobs >= max_jobs:
                    print(f"\nReached maximum job limit ({max_jobs}). Stopping job submission.")
                    break

                if args.spw_filter and spw_id not in args.spw_filter:
                    print(f"Skipping {ms_key} spw{spw_id} (not in filter)")
                    continue

                if args.field_filter:
                    field_name = self.tclean_commands[ms_key]['field_name']
                    if not any(f in field_name for f in args.field_filter):
                        print(f"Skipping {ms_key} spw{spw_id} (field {field_name} not in filter)")
                        continue

                self.run_parallel_imaging(ms_key, spw_id, args)
                launched_jobs += 1

            # Break out of outer loop if we've reached max jobs
            if max_jobs is not None and launched_jobs >= max_jobs:
                break

        if max_jobs is not None:
            print(f"\nSummary: Launched {launched_jobs} out of {total_jobs} total jobs (limited to {max_jobs} max)")
        else:
            print(f"\nSummary: Launched {launched_jobs} out of {total_jobs} total jobs")


def create_cleanup_script(workdir, logdir):
    """Create a cleanup script to remove unnecessary large files."""
    cleanup_script = f"""#!/bin/bash
# DIHCA2 Cleanup Script
# Removes .psf, .model, .residual, and .weight cubes after imaging is complete
# Working directory: {workdir} (high-performance storage)

echo "Starting cleanup of large files in {workdir}"

# Find and remove .psf files
echo "Removing .psf files..."
find {workdir} -name "*.psf" -type d -exec rm -rf {{}} + 2>/dev/null || true

# Find and remove .model files
echo "Removing .model files..."
find {workdir} -name "*.model" -type d -exec rm -rf {{}} + 2>/dev/null || true

# Find and remove .residual files
echo "Removing .residual files..."
find {workdir} -name "*.residual" -type d -exec rm -rf {{}} + 2>/dev/null || true

# Find and remove .weight files
echo "Removing .weight files..."
find {workdir} -name "*.weight" -type d -exec rm -rf {{}} + 2>/dev/null || true

# Find and remove temporary MS files (split products)
echo "Removing temporary split MS files..."
find {workdir} -name "*_spw*.ms" -type d -exec rm -rf {{}} + 2>/dev/null || true

echo "Cleanup complete"

# Log the disk usage after cleanup
du -sh {workdir}/* > {logdir}/cleanup_disk_usage_$(date +%Y%m%d_%H%M%S).log
"""

    cleanup_file = os.path.join(workdir, 'cleanup_large_files.sh')
    with open(cleanup_file, 'w') as f:
        f.write(cleanup_script)

    # Make executable
    os.chmod(cleanup_file, 0o755)

    print(f"Created cleanup script: {cleanup_file}")
    return cleanup_file


def main():
    parser = argparse.ArgumentParser(description='DIHCA2 Job Runner for parallel tclean imaging')

    # Input files
    parser.add_argument('--metadata-file',
                        default='/orange/adamginsburg/salt/dihca2imaging/dihca2_metadata.json',
                        help='Path to metadata JSON file')
    parser.add_argument('--tclean-commands-file',
                        default='/orange/adamginsburg/salt/dihca2imaging/dihca2_tclean_commands.json',
                        help='Path to tclean commands JSON file')

    # Directories
    parser.add_argument('--workdir',
                        default='/red/adamginsburg/dihca/workdir',
                        help='Working directory for imaging (high-performance storage)')
    parser.add_argument('--logdir',
                        default='/red/adamginsburg/logs',
                        help='Log directory (high-performance storage)')

    # SLURM parameters
    parser.add_argument('--account', default='astronomy-dept', help='SLURM account')
    parser.add_argument('--qos', default='astronomy-dept-b', help='SLURM QOS')
    parser.add_argument('--casa-version',
                        default='casa-6.4.3-2-pipeline-2021.3.0.17',
                        help='CASA version to use')

    # Job control
    parser.add_argument('--dry-run', action='store_true',
                        help='Print commands but do not submit jobs')
    parser.add_argument('--redo-completed', action='store_true',
                        help='Redo jobs that are already completed')
    parser.add_argument('--redo-failed', action='store_true',
                        help='Redo jobs that failed')

    # Filters
    parser.add_argument('--spw-filter', type=int, nargs='+',
                        help='Only process these spectral windows')
    parser.add_argument('--field-filter', nargs='+',
                        help='Only process fields containing these strings')
    parser.add_argument('--max-jobs', type=int,
                        help='Maximum number of jobs to submit (useful for testing)')

    # Actions
    parser.add_argument('--create-cleanup-script', action='store_true',
                        help='Create cleanup script and exit')
    parser.add_argument('--run-cleanup', action='store_true',
                        help='Run cleanup script to remove large files')

    args = parser.parse_args()

    # Create cleanup script if requested
    if args.create_cleanup_script:
        create_cleanup_script(args.workdir, args.logdir)
        return

    # Run cleanup if requested
    if args.run_cleanup:
        cleanup_script = os.path.join(args.workdir, 'cleanup_large_files.sh')
        if os.path.exists(cleanup_script):
            print("Running cleanup script...")
            subprocess.run(['bash', cleanup_script])
        else:
            print(f"Cleanup script not found at {cleanup_script}")
            print("Run with --create-cleanup-script first")
        return

    # Check required files exist
    if not os.path.exists(args.metadata_file):
        print(f"Error: Metadata file not found: {args.metadata_file}")
        print("Run inspect_ms_metadata.py first to generate metadata")
        sys.exit(1)

    if not os.path.exists(args.tclean_commands_file):
        print(f"Error: Tclean commands file not found: {args.tclean_commands_file}")
        print("Run inspect_ms_metadata.py first to generate tclean commands")
        sys.exit(1)

    # Create and run job runner
    runner = DIHCA2JobRunner(
        metadata_file=args.metadata_file,
        tclean_commands_file=args.tclean_commands_file,
        workdir=args.workdir,
        logdir=args.logdir,
        account=args.account,
        qos=args.qos,
        casa_version=args.casa_version
    )

    if args.dry_run:
        print("DRY RUN MODE - No jobs will be submitted")

    runner.run_all_jobs(args)


if __name__ == '__main__':
    main()
