#!/usr/bin/env python3
"""
Imaging Job Runner for DIHCA2 grouped sources.

This script:
1. Reads the imaging plan JSON file generated by imaging_plan.py
2. Sets up SLURM jobs using the ACES parallel_tclean functionality
3. Runs jobs in /red for high-performance I/O
4. Moves completed products to /orange for long-term storage
5. Manages job dependencies and cleanup

Uses the same machinery as dihca2_job_runner.py but adapted for the
grouped source imaging plan.
"""

import os
import sys
import json
import glob
import copy
import subprocess
import datetime
import argparse
from pathlib import Path

from aces.imaging.parallel_tclean import parallel_clean_slurm


class ImagingJobRunner:
    def __init__(self, imaging_plan_file,
                 workdir='/red/adamginsburg/dihca/workdir_grouped',
                 logdir='/red/adamginsburg/logs',
                 savedir='/orange/adamginsburg/salt/dihca2imaging/grouped_imaging_products',
                 account='astronomy-dept',
                 qos='astronomy-dept-b',
                 casa_version='casa-6.4.3-2-pipeline-2021.3.0.17'):

        self.imaging_plan_file = imaging_plan_file
        self.workdir = workdir
        self.logdir = logdir
        self.savedir = savedir
        self.account = account
        self.qos = qos
        self.casa_version = casa_version

        # Create directories
        os.makedirs(workdir, exist_ok=True)
        os.makedirs(logdir, exist_ok=True)
        os.makedirs(savedir, exist_ok=True)

        # Load imaging plan
        self.load_imaging_plan()

        # Default parameters for imaging
        # These are smaller groups, so we can use less memory per job
        self.default_parameters = {
            'mem': 64,  # GB - smaller groups need less memory
            'ntasks': 8,  # fewer tasks for smaller images
            'nchan_per': 128,
            'mem_per_cpu': '8gb',
            'jobtime': '48:00:00'  # shorter time for smaller groups
        }

    def load_imaging_plan(self):
        """Load imaging plan from JSON file."""
        print(f"Loading imaging plan from {self.imaging_plan_file}")
        with open(self.imaging_plan_file, 'r') as f:
            self.imaging_plan = json.load(f)

        # Group commands by unique group (remove _spwN suffix)
        self.groups = {}
        for key, cmd in self.imaging_plan.items():
            group_key = key.rsplit('_spw', 1)[0]
            spw = cmd['spw']

            if group_key not in self.groups:
                self.groups[group_key] = {}

            self.groups[group_key][spw] = cmd

        print(f"Loaded {len(self.imaging_plan)} imaging commands")
        print(f"Organized into {len(self.groups)} groups × 4 spectral windows")

        # Validate image sizes
        for key, cmd in self.imaging_plan.items():
            imsize = cmd['imsize']
            if isinstance(imsize, list) and len(imsize) > 0:
                max_imsize = max(imsize)
                if max_imsize > 2048:
                    print(f"Warning: Large imsize {imsize} for {key}")

    def get_running_jobs(self):
        """Get currently running/pending jobs from SLURM."""
        sacct = subprocess.check_output([
            '/opt/slurm/bin/sacct',
            '--format=JobID,JobName%60,Account%15,QOS%17,State,Priority%8,ReqMem%8,CPUTime%15,Elapsed%15,Timelimit%15,NodeList%20'
        ])

        # Parse the output to get job information
        lines = sacct.decode().split('\n')
        jobs = {}
        for line in lines[2:]:  # Skip header lines
            if line.strip():
                parts = line.split()
                if len(parts) >= 5:
                    job_id = parts[0]
                    job_name = parts[1]
                    state = parts[4]
                    jobs[job_name] = {'job_id': job_id, 'state': state}

        return jobs

    def get_file_size_gb(self, path):
        """Get total size of file or directory in GB."""
        if os.path.isfile(path):
            return os.path.getsize(path) / (1024**3)
        elif os.path.isdir(path):
            total = 0
            for dirpath, dirnames, filenames in os.walk(path):
                for f in filenames:
                    fp = os.path.join(dirpath, f)
                    if os.path.exists(fp):
                        total += os.path.getsize(fp)
            return total / (1024**3)
        return 0

    def is_image_blank(self, image_path, max_memory_gb=8):
        """
        Check if a CASA image is blank (all zeros, NaNs, or no variation).
        Uses spectral-cube for memory-efficient validation.

        Parameters:
        -----------
        image_path : str
            Path to CASA image directory or FITS file
        max_memory_gb : float
            Maximum memory to use for loading data (default: 8 GB)

        Returns:
        --------
        bool : True if image is blank/invalid, False if it contains valid data
        str : Reason if blank, None otherwise
        """
        import numpy as np

        if not os.path.exists(image_path):
            return True, "Image does not exist"

        # Check file size first
        file_size_gb = self.get_file_size_gb(image_path)

        if file_size_gb == 0:
            return True, "Image file is empty (0 bytes)"

        print(f"    Validating image ({file_size_gb:.2f} GB)...", end=" ", flush=True)

        # For very large files, skip detailed validation
        if file_size_gb > max_memory_gb * 2:
            print(f"too large, skipping detailed validation")
            # Only do basic checks - if it exists and has size, assume it's okay
            return False, None

        # Use spectral-cube for memory-efficient access
        from spectral_cube import SpectralCube
        from spectral_cube.utils import SpectralCubeWarning
        import warnings
        import time
        t0 = time.time()

        # Load the cube (spectral-cube handles memory efficiently)
        with warnings.catch_warnings():
            warnings.filterwarnings('ignore', category=SpectralCubeWarning)
            warnings.filterwarnings('ignore', category=RuntimeWarning)
            if image_path.endswith('.fits'):
                cube = SpectralCube.read(image_path, format='fits', use_dask=True)
            else:
                cube = SpectralCube.read(image_path, format='casa_image', use_dask=True,)

            # first do a quick check
            minicube = cube[:2]
            minicubestats = minicube.statistics()
            if ((minicubestats['max'] > 0*cube.unit) and
                (minicubestats['max'] - minicubestats['min'] > 0*cube.unit) and
                (minicubestats['rms'] > 1e-10*cube.unit)):
                print(f"QUICKCHECK {os.path.basename(image_path)} OK (min={minicubestats['min']:.3e}, max={minicubestats['max']:.3e}, std={minicubestats['rms']:.3e}).  dt={time.time()-t0:0.3f} seconds")
                return False, None

            # Check if all NaN
            cubestats = cube.statistics()
            data_max = cubestats['max']
            data_min = cubestats['min']
            data_std = cubestats['rms']
            if np.isnan(data_max):
                print("all NaN")
                return True, "All pixels are NaN"

            # Check if all zeros
            if data_max == 0:
                print("all zeros")
                return True, "All pixels are zero"

            # Check if no variation (max == min within tolerance)
            data_min = cube.min()

            if np.abs(data_max - data_min) < 1e-10*cube.unit:
                print(f"no variation (min={data_min}, max={data_max})")
                return True, f"No variation in data (min={data_min}, max={data_max})"

            # Check if RMS is suspiciously low
            data_std = cube.std()
            if data_std < 1e-10*cube.unit:
                print(f"RMS too low ({data_std})")
                return True, f"RMS suspiciously low ({data_std})"

        print(f"{os.path.basename(image_path)} OK (min={data_min:.3e}, max={data_max:.3e}, std={data_std:.3e}).  dt={time.time()-t0:0.3f} seconds")
        return False, None


    def check_completed_merge_job(self, imagename):
        """Check if the merge job has completed successfully by examining output files."""
        expected_image = f"{imagename}.image.pbcor.fits"
        workdir_path = os.path.join(self.workdir, imagename, expected_image)
        savedir_path = os.path.join(self.savedir, expected_image)
        return (os.path.exists(workdir_path), os.path.exists(savedir_path))


    def check_completed_array_tasks(self, imagename, nchan, nchan_per):
        """Check which array tasks have completed successfully by examining output files."""
        completed_tasks = []
        failed_blank_tasks = []
        total_tasks = nchan // nchan_per
        if nchan % nchan_per != 0:
            total_tasks += 1  # Account for partial last chunk

        for task_id in range(total_tasks):
            start = task_id * nchan_per
            # Expected output file name (matches parallel_tclean naming)
            expected_image = f"{imagename}.{start:04d}.{nchan_per:03d}.image.pbcor.fits"

            # Check both workdir and savedir
            workdir_path = os.path.join(self.workdir, imagename, expected_image)
            savedir_path = os.path.join(self.savedir, expected_image)

            for image_path, dirname in [(savedir_path, 'savedir'), (workdir_path, 'workdir')]:

                if os.path.exists(image_path):
                    # Check if the image is blank
                    is_blank, reason = self.is_image_blank(image_path)

                    if is_blank:
                        print(f"  WARNING: Task {task_id} produced blank image: {reason}")
                        print(f"           Deleting blank image: {image_path}")
                        failed_blank_tasks.append(task_id)

                        # Delete the blank image
                        if os.path.isdir(image_path):
                            import shutil
                            shutil.rmtree(image_path)
                        else:
                            os.remove(image_path)
                        print(f"           Deleted blank image successfully")
                    else:
                        print(f"  Task {task_id} produced valid image in {dirname}")
                        completed_tasks.append(task_id)
                        break

        if failed_blank_tasks:
            print(f"  Found {len(failed_blank_tasks)} blank images (will be reprocessed)")

        return completed_tasks, total_tasks

    def should_skip_job(self, jobname, running_jobs, args, **job_params):
        """Determine if a job should be skipped based on its current status."""
        if jobname not in running_jobs:
            return False, "Job not found in queue", None

        state = running_jobs[jobname]['state']
        job_id = running_jobs[jobname]['job_id']

        if state == 'RUNNING':
            return True, f"Job {jobname} is RUNNING as {job_id}", None
        elif state == 'PENDING':
            return True, f"Job {jobname} is PENDING as {job_id}", None
        elif state == 'COMPLETED':
            if args.redo_completed:
                return False, f"Redoing COMPLETED job {jobname} ({job_id})", None
            else:
                return True, f"Job {jobname} is COMPLETED as {job_id}", None
        elif state == 'FAILED':
            if args.redo_failed:
                # Check which array tasks completed successfully
                if 'imagename' in job_params and 'nchan' in job_params and 'nchan_per' in job_params:
                    completed_tasks, total_tasks = self.check_completed_array_tasks(
                        job_params['imagename'],
                        job_params['nchan'],
                        job_params['nchan_per']
                    )

                    if len(completed_tasks) == total_tasks:
                        return True, f"Job {jobname} FAILED but all {total_tasks} array tasks completed successfully", None
                    elif len(completed_tasks) > 0:
                        # Some tasks completed - return list of tasks that need to be rerun
                        failed_tasks = [i for i in range(total_tasks) if i not in completed_tasks]
                        return False, f"Redoing FAILED job {jobname} ({job_id}) - {len(completed_tasks)}/{total_tasks} tasks completed", failed_tasks
                    else:
                        return False, f"Redoing FAILED job {jobname} ({job_id}) - no tasks completed", None
                else:
                    return False, f"Redoing FAILED job {jobname} ({job_id})", None
            else:
                return True, f"Job {jobname} is FAILED as {job_id}", None
        elif state == 'TIMEOUT':
            return False, f"Restarting TIMEOUT job {jobname} ({job_id})", None

        return False, f"Job {jobname} has state {state}", None

    def _run_selective_parallel_clean(self, parallel_params, failed_tasks):
        """Run parallel_clean_slurm with selective array tasks by modifying the SLURM command."""
        import tempfile
        import shutil

        # Remove the selective tasks parameter before calling parallel_clean_slurm
        selective_params = parallel_params.copy()
        if '_selective_tasks' in selective_params:
            del selective_params['_selective_tasks']

        # Create array specification for failed tasks
        if len(failed_tasks) == 1:
            array_spec = str(failed_tasks[0])
        else:
            # Convert list of task IDs to SLURM array format (e.g., "1,3,5-7,10")
            array_spec = self._format_slurm_array(failed_tasks)

        print(f"  Selective array tasks: {array_spec}")

        # We need to monkey-patch the parallel_clean_slurm function to use our custom array spec
        # Store original subprocess.check_output
        original_check_output = subprocess.check_output

        def patched_check_output(cmd_list):
            # Modify the SLURM command to use our selective array specification
            if isinstance(cmd_list, list) and len(cmd_list) > 0 and 'sbatch' in cmd_list[0]:
                # Find and replace the --array parameter
                for i, arg in enumerate(cmd_list):
                    if arg.startswith('--array='):
                        cmd_list[i] = f'--array={array_spec}'
                        break
                print(f"Modified SLURM command for selective resubmission: {' '.join(cmd_list)}")

            return original_check_output(cmd_list)

        # Temporarily patch subprocess.check_output
        subprocess.check_output = patched_check_output

        try:
            # Call the original function with patched subprocess
            parallel_clean_slurm(**selective_params)
        finally:
            # Restore original function
            subprocess.check_output = original_check_output

    def _format_slurm_array(self, task_ids):
        """Format a list of task IDs into SLURM array specification (e.g., "1,3,5-7,10")."""
        if not task_ids:
            return ""

        task_ids = sorted(task_ids)
        ranges = []
        start = task_ids[0]
        end = start

        for i in range(1, len(task_ids)):
            if task_ids[i] == end + 1:
                end = task_ids[i]
            else:
                if start == end:
                    ranges.append(str(start))
                else:
                    ranges.append(f"{start}-{end}")
                start = end = task_ids[i]

        # Add the last range
        if start == end:
            ranges.append(str(start))
        else:
            ranges.append(f"{start}-{end}")

        return ",".join(ranges)

    def run_parallel_imaging(self, group_name, spw, args):
        """Run parallel tclean imaging for a specific group and spectral window.

        Returns:
        --------
        tuple: (status, reason) where status is 'submitted' or 'skipped'
        """

        # Get imaging command
        cmd = self.groups[group_name][spw]

        # Create job name
        jobname = f"imaging_{group_name}_spw{spw}"

        print(f"\nSetting up imaging job for {group_name} spw{spw}")
        print(f"  Sources: {cmd['metadata']['n_sources']}")
        print(f"  FOV: {cmd['metadata']['fov_arcsec']:.2f} arcsec")
        print(f"  Image size: {cmd['imsize'][0]}x{cmd['imsize'][1]} pixels")

        # Get number of channels
        nchan = cmd['nchan']

        # Set up job parameters
        imagename = f"{group_name}_spw{spw}"
        job_workdir = os.path.join(self.workdir, imagename)

        # First check if workdir exists with output products
        # This is a quick check to skip jobs that are actively being processed
        # Adam (not the AI) added: this is not a valid check.  The workdir always exists and can have invalid files in it.
        # if os.path.exists(job_workdir):
        #     # Check if there are any image files in the workdir
        #     image_files = glob.glob(os.path.join(job_workdir, "*.image"))
        #     if len(image_files) > 0:
        #         print(f"Skipping {jobname}: Working directory exists with {len(image_files)} image files")
        #         print(f"  Directory: {job_workdir}")
        #         return ('skipped', 'workdir_exists')

        # Check if all output products already exist
        job_params = {
            'imagename': imagename,
            'nchan': nchan,
            'nchan_per': self.default_parameters['nchan_per']
        }

        work_completed, save_completed = self.check_completed_merge_job(job_params['imagename'])

        merge_only = False
        if save_completed:
            print(f"For {jobname}, the merge job has completed successfully and the output products exist in the savedir")
            return ('skipped', 'save_completed')
        elif work_completed:
            print(f"For {jobname}, the merge job has completed successfully and the output products exist in the workdir, but they haven't been copied over to the savedir.")
            merge_only = True

        completed_tasks, total_tasks = self.check_completed_array_tasks(
            job_params['imagename'],
            job_params['nchan'],
            job_params['nchan_per']
        )

        if len(completed_tasks) == total_tasks:
            print(f"For {jobname}, all {total_tasks} array tasks already completed (output products exist), but merge wasn't completed")
            merge_only = True
        elif len(completed_tasks) > 0:
            print(f"Found {len(completed_tasks)}/{total_tasks} completed array tasks for {jobname}")

        # Check SLURM queue status
        running_jobs = self.get_running_jobs()

        # Check if this job (or any variant) is already in the queue
        # Jobs get suffixes like _split, _arr, _merge when submitted
        related_jobs = [name for name in running_jobs.keys() if name.startswith(jobname)]
        if related_jobs:
            for job in related_jobs:
                state = running_jobs[job]['state']
                job_id = running_jobs[job]['job_id']
                if state in ['RUNNING', 'PENDING']:
                    print(f"Skipping {jobname}: Job already in queue as {job} ({state}, job_id={job_id})")
                    return ('skipped', 'in_queue')

        should_skip, reason, failed_tasks = self.should_skip_job(jobname, running_jobs, args, **job_params)
        if should_skip:
            print(f"Skipping {jobname}: {reason}")
            return ('skipped', reason)

        # If we have some completed tasks but job is not in queue, only submit missing tasks
        # Check for related jobs (with suffixes) not just exact match
        job_in_queue = any(name.startswith(jobname) for name in running_jobs.keys())
        if len(completed_tasks) > 0 and not job_in_queue:
            failed_tasks = [i for i in range(total_tasks) if i not in completed_tasks]
            print(f"Job {jobname} not in queue but {len(completed_tasks)}/{total_tasks} tasks completed")
            print(f"Will submit only missing array tasks")

            if len(completed_tasks) == total_tasks:
                print(f"All {total_tasks} tasks completed - will only submit merge job")
                merge_only = True

        # Create working directory for this job
        job_workdir = os.path.join(self.workdir, imagename)
        os.makedirs(job_workdir, exist_ok=True)

        # Adjust memory based on image size
        imsize = cmd['imsize'][0]
        if imsize >= 1024:
            mem = 96  # GB for larger images
            ntasks = 12
        else:
            mem = 64  # GB for smaller images
            ntasks = 8

        # Parameters for parallel_clean_slurm
        parallel_params = {
            'nchan': nchan,
            'imagename': imagename,
            'spw': spw,
            'start': cmd.get('start', 0),
            'width': cmd.get('width', 1),
            'field': cmd['field'],
            'vis': cmd['vis'],
            'phasecenter': cmd.get('phasecenter'),  # Use custom phase center for groups
            'jobname': jobname,
            'workdir': job_workdir,
            'logdir': self.logdir,
            'account': self.account,
            'qos': self.qos,
            'jobtime': self.default_parameters['jobtime'],
            'CASAVERSION': self.casa_version,
            'ntasks': ntasks,
            'nchan_per': self.default_parameters['nchan_per'],
            'mem_per_cpu': self.default_parameters['mem_per_cpu'],
            'dry': args.dry_run,
            'savedir': self.savedir,
            'remove_incomplete_psf': True,
            'remove_incomplete_weight': True,
            # Only keep image and psf
            'suffixes_to_merge_and_export': ['image', 'image.pbcor', 'model']
        }

        # Add remaining tclean parameters from the command
        # Exclude parameters already set and metadata
        exclude_keys = ['vis', 'field', 'spw', 'imagename', 'nchan', 'start', 'width',
                       'phasecenter', 'metadata']
        for key, value in cmd.items():
            if key not in exclude_keys and key not in parallel_params:
                parallel_params[key] = value

        # Handle selective array resubmission for failed tasks
        if failed_tasks is not None:
            print(f"Selective resubmission: running only tasks {failed_tasks}")
            parallel_params['_selective_tasks'] = failed_tasks

        if merge_only:
            parallel_params['merge_only'] = True

        print(f"Launching parallel_clean_slurm:")
        print(f"  Job name: {jobname}")
        print(f"  Image: {imagename}")
        print(f"  Working dir: {job_workdir}")
        print(f"  Save dir: {self.savedir}")
        print(f"  Memory: {mem}GB, Tasks: {ntasks}")
        print(f"  N channels: {nchan}, Channels per task: {parallel_params['nchan_per']}")

        # Call parallel_clean_slurm
        if failed_tasks is not None and len(failed_tasks) > 0:
            self._run_selective_parallel_clean(parallel_params, failed_tasks)
        elif failed_tasks is not None and len(failed_tasks) == 0:
            print(f"No array tasks to submit for {jobname} - all tasks already completed")
            if merge_only:
                print(f"Will submit merge job for {jobname}")
                parallel_clean_slurm(**parallel_params)
            else:
                return ('skipped', 'no_tasks_to_submit')
        else:
            parallel_clean_slurm(**parallel_params)

        print(f"Successfully launched job {jobname}")
        if merge_only:
            return ('submitted_mergeonly', None)
        else:
            return ('submitted', None)

    def validate_and_cleanup_products(self, group_name, spw, detailed_check=True):
        """
        Comprehensive validation of imaging products with cleanup of blank files.

        Performs multi-level validation:
        1. Check if merged image exists
        2. Validate merged image data quality
        3. If merged image is blank, check individual sub-images
        4. Remove blank sub-images and associated metadata

        Parameters:
        -----------
        group_name : str
            Group name (e.g., G008.672-00.682_group1)
        spw : int
            Spectral window number
        detailed_check : bool
            If True, perform detailed validation of individual sub-images

        Returns:
        --------
        dict : Validation results with keys:
            - 'merged_exists': bool
            - 'merged_valid': bool
            - 'merged_reason': str (if invalid)
            - 'sub_images_checked': int
            - 'sub_images_blank': int
            - 'sub_images_removed': int
            - 'cleanup_performed': bool
        """
        imagename = f"{group_name}_spw{spw}"
        results = {
            'merged_exists': False,
            'merged_valid': False,
            'merged_reason': None,
            'sub_images_checked': 0,
            'sub_images_blank': 0,
            'sub_images_removed': 0,
            'cleanup_performed': False
        }

        print(f"\n=== Validating imaging products for {imagename} ===")

        # Step 1: Check if merged image exists
        merged_paths = []
        # only accept .image.pbcor.fits; redo others
        for suffix in [".image.pbcor.fits"]: # ['.image', '.image.fits']:
            merged_path = os.path.join(self.savedir, f"{imagename}{suffix}")
            if os.path.exists(merged_path):
                merged_paths.append(merged_path)
                results['merged_exists'] = True
                break

        if not results['merged_exists']:
            print(f"  ✗ No merged image found in {self.savedir}")
            if detailed_check:
                print(f"  → Checking individual sub-images for cleanup...")
            else:
                return results
        else:
            print(f"  ✓ Merged image found: {os.path.basename(merged_paths[0])}")

        # Step 2: Validate merged image if it exists
        if results['merged_exists']:
            merged_path = merged_paths[0]
            is_blank, reason = self.is_image_blank(merged_path, max_memory_gb=16)

            if is_blank:
                results['merged_valid'] = False
                results['merged_reason'] = reason
                print(f"  ✗ Merged image is blank: {reason}")
                print(f"  → Will check individual sub-images to identify problematic chunks")
            else:
                results['merged_valid'] = True
                print(f"  ✓ Merged image contains valid data")
                # If merged image is valid, no need to check sub-images unless requested
                if not detailed_check:
                    return results

        # Step 3: Check individual sub-images (if merged is blank or detailed_check=True)
        if not results['merged_valid'] or detailed_check:
            print(f"  → Checking individual sub-images...")

            # Get expected number of sub-images
            if group_name in self.groups and spw in self.groups[group_name]:
                nchan = self.groups[group_name][spw]['nchan']
                nchan_per = self.default_parameters['nchan_per']
                total_tasks = nchan // nchan_per
                if nchan % nchan_per != 0:
                    total_tasks += 1
            else:
                # Fallback: scan for existing sub-images
                total_tasks = 0
                pattern = os.path.join(self.workdir, imagename, f"{imagename}.*.image")
                existing_images = glob.glob(pattern)
                if existing_images:
                    # Extract task numbers from filenames
                    task_nums = []
                    for img_path in existing_images:
                        basename = os.path.basename(img_path)
                        # Format: imagename.SSSS.CCC.image where SSSS=start, CCC=nchan
                        parts = basename.split('.')
                        if len(parts) >= 4 and parts[-1] == 'image':
                            try:
                                start_chan = int(parts[-3])
                                task_num = start_chan // nchan_per
                                task_nums.append(task_num)
                            except ValueError:
                                continue
                    total_tasks = max(task_nums) + 1 if task_nums else 0

            print(f"    Expected sub-images: {total_tasks}")

            blank_images = []
            checked_images = []

            # Check each sub-image
            for task_id in range(total_tasks):
                start = task_id * nchan_per
                expected_image = f"{imagename}.{start:04d}.{nchan_per:03d}.image"

                # Check both workdir and savedir
                image_paths = [
                    os.path.join(self.workdir, imagename, expected_image),
                    os.path.join(self.savedir, expected_image)
                ]

                image_path = None
                for path in image_paths:
                    if os.path.exists(path):
                        image_path = path
                        break

                if image_path:
                    checked_images.append(image_path)
                    results['sub_images_checked'] += 1

                    print(f"    Checking task {task_id}: {os.path.basename(image_path)}")
                    is_blank, reason = self.is_image_blank(image_path, max_memory_gb=8)

                    if is_blank:
                        results['sub_images_blank'] += 1
                        blank_images.append((image_path, task_id, reason))
                        print(f"      ✗ BLANK: {reason}")
                    else:
                        print(f"      ✓ Valid data")
                else:
                    print(f"    Task {task_id}: Sub-image not found")

            # Step 4: Remove blank sub-images and associated files
            if blank_images:
                print(f"\n  → Cleaning up {len(blank_images)} blank sub-images...")
                results['cleanup_performed'] = True

                for image_path, task_id, reason in blank_images:
                    print(f"    Removing blank task {task_id}: {reason}")

                    # Get the base name without extension
                    if image_path.endswith('.image'):
                        base_path = image_path[:-6]  # Remove '.image'
                    else:
                        base_path = image_path

                    # List of suffixes to remove
                    suffixes_to_remove = ['.image', '.psf', '.pb', '.model', '.residual',
                                         '.sumwt', '.weight', '.image.pbcor']

                    removed_files = []
                    for suffix in suffixes_to_remove:
                        file_path = f"{base_path}{suffix}"

                        if os.path.exists(file_path):
                            try:
                                if os.path.isdir(file_path):
                                    import shutil
                                    shutil.rmtree(file_path)
                                else:
                                    os.remove(file_path)
                                removed_files.append(os.path.basename(file_path))
                                results['sub_images_removed'] += 1
                            except Exception as e:
                                print(f"      Warning: Could not remove {file_path}: {e}")

                    if removed_files:
                        print(f"      Removed: {', '.join(removed_files)}")

            # Step 5: If merged image exists but is blank, remove it too
            if results['merged_exists'] and not results['merged_valid']:
                print(f"\n  → Removing blank merged image...")

                for merged_path in merged_paths:
                    # Remove merged image and associated files
                    if merged_path.endswith('.fits'):
                        base_merged = merged_path[:-5]  # Remove '.fits'
                    else:
                        base_merged = merged_path
                    # then, next:
                    if base_merged.endswith('.image'):
                        base_merged = base_merged[:-6]  # Remove '.image'
                    else:
                        base_merged = base_merged

                    merged_suffixes = ['.image', '.image.fits', '.psf', '.pb', '.model',
                                     '.residual', '.sumwt', '.weight', '.image.pbcor']

                    for suffix in merged_suffixes:
                        merged_file = f"{base_merged}{suffix}"
                        if os.path.exists(merged_file):
                            try:
                                if os.path.isdir(merged_file):
                                    import shutil
                                    shutil.rmtree(merged_file)
                                else:
                                    os.remove(merged_file)
                                print(f"    Removed: {os.path.basename(merged_file)}")
                            except Exception as e:
                                print(f"    Warning: Could not remove {merged_file}: {e}")

                results['merged_exists'] = False
                results['cleanup_performed'] = True

        # Summary
        print(f"\n  === Validation Summary for {imagename} ===")
        print(f"  Merged image exists: {results['merged_exists']}")
        print(f"  Merged image valid: {results['merged_valid']}")
        if results['merged_reason']:
            print(f"  Merged image issue: {results['merged_reason']}")
        print(f"  Sub-images checked: {results['sub_images_checked']}")
        print(f"  Sub-images blank: {results['sub_images_blank']}")
        print(f"  Files removed: {results['sub_images_removed']}")
        print(f"  Cleanup performed: {results['cleanup_performed']}")

        return results

    def validate_final_products(self, group_name, spw):
        """
        Legacy method for backward compatibility.
        Now calls the comprehensive validate_and_cleanup_products method.
        """
        results = self.validate_and_cleanup_products(group_name, spw, detailed_check=False)
        return results['merged_exists'] and results['merged_valid']

    def run_all_jobs(self, args):
        """Run imaging jobs for all groups and spectral windows."""

        # Check current job status before starting
        running_jobs = self.get_running_jobs()
        if running_jobs:
            print(f"\nCurrent SLURM queue status:")
            running_count = sum(1 for job in running_jobs.values() if job['state'] == 'RUNNING')
            pending_count = sum(1 for job in running_jobs.values() if job['state'] == 'PENDING')
            merge_running = [name for name in running_jobs.keys()
                           if name.endswith('_merge') and running_jobs[name]['state'] == 'RUNNING']

            print(f"  RUNNING jobs: {running_count}")
            print(f"  PENDING jobs: {pending_count}")
            if merge_running:
                print(f"  RUNNING merge jobs: {', '.join(merge_running)}")
            print()

        total_jobs = 0
        launched_jobs = 0
        skipped_jobs = 0
        mergeonly_jobs = 0
        max_jobs = getattr(args, 'max_jobs', 10)

        # Track skip reasons
        skip_reasons = {}

        # max_jobs = 0 means unlimited
        unlimited = (max_jobs == 0)
        if unlimited:
            max_jobs = None

        # Process each group
        for group_name in sorted(self.groups.keys()):
            # Apply field filter if specified
            if args.field_filter:
                if not any(f in group_name for f in args.field_filter):
                    continue

            # Process each spectral window
            for spw in sorted(self.groups[group_name].keys()):
                total_jobs += 1

                # Check if we've reached the maximum number of jobs
                if max_jobs is not None and launched_jobs >= max_jobs:
                    print(f"\nReached maximum job limit ({max_jobs}). Stopping job submission.")
                    print(f"Use --max-jobs 0 for unlimited, or --max-jobs N to increase limit.")
                    break

                # Apply SPW filter if specified
                if args.spw_filter and spw not in args.spw_filter:
                    print(f"Skipping {group_name} spw{spw} (not in SPW filter)")
                    skipped_jobs += 1
                    skip_reasons['spw_filter'] = skip_reasons.get('spw_filter', 0) + 1
                    continue

                result = self.run_parallel_imaging(group_name, spw, args)
                if result:
                    status, reason = result
                    if 'submitted' in status:
                        launched_jobs += 1
                    elif status == 'skipped':
                        skipped_jobs += 1
                        # Track the reason
                        skip_reasons[reason] = skip_reasons.get(reason, 0) + 1
                    if 'mergeonly' in status:
                        mergeonly_jobs += 1

                # Post-imaging validation and cleanup (if enabled)
                if args.validate_after_imaging:
                    print(f"\nPerforming post-imaging validation for {group_name} spw{spw}...")
                    validation_results = self.validate_and_cleanup_products(group_name, spw, detailed_check=True)

                    if validation_results['cleanup_performed']:
                        print(f"  → Cleanup completed. Rerun imaging for this group to regenerate clean data.")
                    elif validation_results['merged_valid']:
                        print(f"  → Validation passed. Products are ready for analysis.")
                    else:
                        print(f"  → No valid products found. Check imaging logs and rerun if needed.")

            # Break out of outer loop if we've reached max jobs
            if max_jobs is not None and launched_jobs >= max_jobs:
                break

        print(f"\n{'='*60}")
        print(f"JOB SUBMISSION SUMMARY")
        print(f"{'='*60}")
        if unlimited:
            print(f"Jobs submitted: {launched_jobs}")
        else:
            print(f"Jobs submitted: {launched_jobs} (max: {args.max_jobs})")
        print(f"Jobs skipped: {skipped_jobs}")
        print(f"Jobs evaluated: {total_jobs}")
        print(f"Merge-only jobs: {mergeonly_jobs}")

        # Show skip reasons if any
        if skip_reasons:
            print(f"\nSkip reasons:")
            # Create human-readable labels
            reason_labels = {
                'workdir_exists': 'Working directory exists with images',
                'all_completed': 'All array tasks already completed',
                'in_queue': 'Job already in SLURM queue',
                'no_tasks_to_submit': 'No tasks to submit (all completed)',
                'spw_filter': 'Filtered by SPW selection',
                'Final product exists': 'Final product exists',
                'Waiting for split job': 'Waiting for split job',
            }

            for reason, count in sorted(skip_reasons.items(), key=lambda x: x[1], reverse=True):
                label = reason_labels.get(reason, reason)
                print(f"  {label}: {count}")

        if not unlimited and args.max_jobs < 844:
            print(f"\nTo submit more jobs, use --max-jobs N (or 0 for unlimited)")



def main():
    parser = argparse.ArgumentParser(
        description='SLURM Job Runner for DIHCA2 grouped source imaging',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This script submits CASA imaging jobs to SLURM for grouped sources.

Key features:
  - Jobs run in /red for high-performance I/O
  - Completed products automatically moved to /orange
  - Memory allocation scaled to image size
  - Automatic handling of failed array tasks
  - Job status checking to avoid duplicate submissions

Example usage:
  # Test with dry run
  python imaging_job_runner.py --dry-run --max-jobs 2

  # Submit all jobs
  python imaging_job_runner.py

  # Submit only specific field
  python imaging_job_runner.py --field-filter G008.672-00.682

  # Submit only one spectral window
  python imaging_job_runner.py --spw-filter 0 --max-jobs 10

  # Redo failed jobs
  python imaging_job_runner.py --redo-failed
"""
    )

    # Input files
    parser.add_argument('--imaging-plan',
                        default='/orange/adamginsburg/salt/dihca2imaging/dihca2_imaging_plan.json',
                        help='Path to imaging plan JSON file')

    # Directories
    parser.add_argument('--workdir',
                        default='/red/adamginsburg/dihca/workdir_grouped',
                        help='Working directory for imaging (high-performance /red storage)')
    parser.add_argument('--logdir',
                        default='/red/adamginsburg/logs',
                        help='Log directory (high-performance /red storage)')
    parser.add_argument('--savedir',
                        default='/orange/adamginsburg/salt/dihca2imaging/grouped_imaging_products',
                        help='Final output directory (/orange long-term storage)')

    # SLURM parameters
    parser.add_argument('--account', default='astronomy-dept', help='SLURM account')
    parser.add_argument('--qos', default='astronomy-dept-b', help='SLURM QOS')
    parser.add_argument('--casa-version',
                        default='casa-6.7.2-42-py3.12.el8',
                        help='CASA version to use')

    # Job control
    parser.add_argument('--dry-run', action='store_true',
                        help='Print commands but do not submit jobs')
    parser.add_argument('--redo-completed', action='store_true',
                        help='Redo jobs that are already completed')
    parser.add_argument('--redo-failed', action='store_true',
                        help='Redo jobs that failed (only resubmits missing array tasks)')

    # Filters
    parser.add_argument('--spw-filter', type=int, nargs='+',
                        help='Only process these spectral windows (0-3)')
    parser.add_argument('--field-filter', nargs='+',
                        help='Only process groups containing these strings in their name')
    parser.add_argument('--max-jobs', type=int, default=10,
                        help='Maximum number of jobs to submit (default: 10, use 0 for unlimited)')

    # Actions
    parser.add_argument('--validate-products', action='store_true',
                        help='Validate all existing products and delete blank ones')
    parser.add_argument('--validate-after-imaging', action='store_true',
                        help='Perform comprehensive validation after each imaging job')
    parser.add_argument('--check-sub-images', action='store_true',
                        help='When validating, also check individual sub-images for problems')

    args = parser.parse_args()

    # Validate products if requested
    if args.validate_products:
        print("Validating existing imaging products...")
        print(f"Checking products in: {args.savedir}")
        print()

        # Load imaging plan to know what to check
        if not os.path.exists(args.imaging_plan):
            print(f"Error: Imaging plan file not found: {args.imaging_plan}")
            sys.exit(1)

        runner = ImagingJobRunner(
            imaging_plan_file=args.imaging_plan,
            workdir=args.workdir,
            logdir=args.logdir,
            savedir=args.savedir,
            account=args.account,
            qos=args.qos,
            casa_version=args.casa_version
        )

        total_checked = 0
        total_blank = 0
        total_valid = 0

        for group_name in sorted(runner.groups.keys()):
            # Apply field filter if specified
            if args.field_filter:
                if not any(f in group_name for f in args.field_filter):
                    continue

            for spw in sorted(runner.groups[group_name].keys()):
                # Apply SPW filter if specified
                if args.spw_filter and spw not in args.spw_filter:
                    continue

                total_checked += 1
                print(f"Checking {group_name} spw{spw}...")
                validation_results = runner.validate_and_cleanup_products(group_name, spw, detailed_check=True)

                if validation_results['merged_valid']:
                    total_valid += 1
                elif validation_results['merged_exists']:
                    # Product exists but is blank
                    total_blank += 1

        print()
        print("="*60)
        print("VALIDATION SUMMARY")
        print("="*60)
        print(f"Total checked:  {total_checked}")
        print(f"Valid products: {total_valid}")
        print(f"Blank products: {total_blank} (deleted)")
        print(f"Missing:        {total_checked - total_valid - total_blank}")
        print()

        if total_blank > 0:
            print("Blank products have been deleted. Rerun imaging for these groups.")

        return


    # Check required files exist
    if not os.path.exists(args.imaging_plan):
        print(f"Error: Imaging plan file not found: {args.imaging_plan}")
        print("Run imaging_plan.py first to generate the imaging plan")
        sys.exit(1)

    # Create and run job runner
    runner = ImagingJobRunner(
        imaging_plan_file=args.imaging_plan,
        workdir=args.workdir,
        logdir=args.logdir,
        savedir=args.savedir,
        account=args.account,
        qos=args.qos,
        casa_version=args.casa_version
    )

    if args.dry_run:
        print("\n" + "="*60)
        print("DRY RUN MODE - No jobs will be submitted")
        print("="*60 + "\n")

    runner.run_all_jobs(args)


if __name__ == '__main__':
    os.chdir('/red/adamginsburg/dihca/shellscripts/')
    main()
