"""Per-source line-list appendices for the paper.

For every analyzed target, emit an appendix subsection with the full set of
IDENTIFIED lines toward the brightest mm continuum source:

  (a) pipeline-measured target lines (NaCl/KCl/H2O/RRL/SO/SiO/SiS) at
      >=5 sigma, from analysis_products/<target>/*/line_measurements.csv;
  (b) where an XCLASS hot-core model was run (find_contaminants_from_xclass),
      every modeled transition above INTENSITY_MIN_K -- i.e. the COM forest
      (CH3OH, CH3OCHO, ...).

Writes demography_2026/source_appendices.tex (one deluxetable per source).
Sources with an XCLASS model get the full COM list; the rest list their
pipeline detections. Frequencies in GHz, sorted ascending.
"""
import glob
import re
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

ROOT = Path("/orange/adamginsburg/salt/survey_2026")
OUT = Path("/orange/adamginsburg/salt/demography_2026/source_appendices.tex")
INTENSITY_MIN_K = 2.75   # above the 2.7 K CMB floor XCLASS reports
MAX_XCLASS_LINES = 200   # cap per source; line-rich hot cores (Orion-BN
                         # models ~7000 lines) would be unusable otherwise.
                         # Keep the brightest MAX by modeled T_B; note the rest.

import find_contaminants_from_xclass as fc  # noqa: E402
from build_xclass_labels import tex_label    # noqa: E402


def display_name(target):
    try:
        from build_detections_table import latex_source_name
        return latex_source_name(target)
    except Exception:
        return target.replace("_", r"\_")


def pipeline_lines(target):
    """>=5 sigma target-species lines at the brightest source, deduped."""
    rows = []
    for lm in glob.glob(str(ROOT / f"analysis_products/{target}/*/line_measurements.csv")):
        try:
            d = pd.read_csv(lm)
        except (pd.errors.EmptyDataError, FileNotFoundError):
            continue
        if not {"line", "group", "rest_GHz", "snr"}.issubset(d.columns):
            continue
        d = d[d["snr"] >= 5.0]
        for _, r in d.iterrows():
            rows.append((float(r["rest_GHz"]), str(r["group"]),
                         str(r["line"]), float(r["snr"])))
    # dedupe by (line, 1 MHz)
    seen = set(); out = []
    for fr, grp, line, snr in sorted(rows, key=lambda x: -x[3]):
        k = (line, round(fr, 3))
        if k in seen:
            continue
        seen.add(k); out.append((fr, grp, line, snr))
    return sorted(out)


def xclass_job_for(target):
    """Authoritative per-target job lookup via xclass_fits/<t>/job_dir.txt
    (avoids find_latest_job substring collisions, e.g. NGC6334I vs
    NGC6334IN). Falls back to find_latest_job by target name."""
    jf = ROOT / "xclass_fits" / target / "job_dir.txt"
    if jf.exists():
        job = Path(jf.read_text().strip())
        if job.exists():
            return job
    return fc.find_latest_job(target)


def xclass_lines(target):
    """Returns (lines, n_total) where lines is the brightest
    MAX_XCLASS_LINES modeled transitions (freq_GHz, mol, T_K) sorted by
    frequency, and n_total is the count above INTENSITY_MIN_K."""
    job = xclass_job_for(target)
    if job is None:
        return None
    tt = job / "transition_energies.dat"
    if not tt.exists():
        return None
    df = fc.parse_transition_table(tt)
    df = df[df["T_K"].astype(float) >= INTENSITY_MIN_K].copy()
    if df.empty:
        return ([], 0)
    df["bin"] = (df["rest_MHz"] / 0.5).round().astype(int)
    df = (df.reindex(df["T_K"].abs().sort_values(ascending=False).index)
            .drop_duplicates("bin"))
    n_total = len(df)
    df = df.head(MAX_XCLASS_LINES).sort_values("rest_MHz")
    lines = [(float(r["rest_MHz"]) / 1000.0, str(r["mol"]),
              float(r["T_K"])) for _, r in df.iterrows()]
    return (lines, n_total)


def line_tex(name):
    if name == "H2O_5_15-4_22_232":
        return r"H$_2$O $v_2${=}1 5(5,0)-6(4,3)"
    return name.replace("_", r"\_")


# label -> (target dir, proposal); reuse XCLASS target map + all analyzed dirs
def main():
    xmap = {label: t for label, (t, _p) in fc.TARGET_PROP.items()}
    analyzed = sorted(
        p.parent.name for p in ROOT.glob("analysis_products/*/report.json"))
    # include every target that has an XCLASS job (xclass_fits/<t>/job_dir.txt)
    # even if it lacks a report.json, plus the legacy TARGET_PROP entries.
    xfit = [d.name for d in (ROOT / "xclass_fits").glob("*")
            if (d / "job_dir.txt").exists()]
    targets = sorted(set(analyzed) | set(xmap.values()) | set(xfit))

    out = [r"% Auto-generated by build_source_appendices.py",
           r"\section{Per-source identified line lists}",
           r"\label{app:linelists}",
           r"For each analyzed source we list the identified lines toward the "
           r"brightest mm continuum core: pipeline-measured target-species "
           r"lines ($\geq5\sigma$: NaCl, KCl, H$_2$O, RRL, SO, SiO, SiS) and, "
           r"where an XCLASS hot-core model was fitted, every modeled "
           r"transition above $" + f"{INTENSITY_MIN_K}" + r"$\,K "
           r"(the complex-organic-molecule forest). Frequencies are rest "
           r"frequencies in GHz.",
           ""]

    n_written = 0
    for tgt in targets:
        pl = pipeline_lines(tgt)
        xres = xclass_lines(tgt)   # per-target job via xclass_fits/<t>/
        xl = xres[0] if xres else None
        n_total = xres[1] if xres else 0
        if not pl and not xl:
            continue
        n_written += 1
        disp = display_name(tgt)
        out.append(r"\subsection{" + disp + r"}")
        # pipeline target lines
        if pl:
            out.append(r"\begin{deluxetable}{lccc}")
            out.append(r"\tabletypesize{\footnotesize}")
            out.append(r"\tablecaption{" + disp + r": pipeline-detected "
                       r"target-species lines ($\geq5\sigma$).}")
            out.append(r"\tablehead{\colhead{Species} & \colhead{Line} & "
                       r"\colhead{$\nu_\mathrm{rest}$ (GHz)} & "
                       r"\colhead{S/N}}")
            out.append(r"\startdata")
            for fr, grp, line, snr in pl:
                out.append(f"{grp} & {line_tex(line)} & {fr:.4f} & "
                           f"{snr:.1f} \\\\")
            out.append(r"\enddata")
            out.append(r"\end{deluxetable}")
        # XCLASS COM forest
        if xl:
            out.append(r"\startlongtable")
            out.append(r"\begin{deluxetable}{lcc}")
            out.append(r"\tabletypesize{\footnotesize}")
            _cap = (disp + r": XCLASS-modeled transitions above " +
                    f"{INTENSITY_MIN_K}" +
                    r"\,K (complex-organic and hot-core lines)")
            if n_total > len(xl):
                _cap += (r"; the " + f"{len(xl)}" + r" brightest of "
                         + f"{n_total}" + r" such lines are shown")
            out.append(r"\tablecaption{" + _cap + r".}")
            out.append(r"\tablehead{\colhead{Species} & "
                       r"\colhead{$\nu_\mathrm{rest}$ (GHz)} & "
                       r"\colhead{$T_B^\mathrm{model}$ (K)}}")
            out.append(r"\startdata")
            for fr, mol, tk in xl:
                out.append(f"{tex_label(mol, '')} & {fr:.4f} & {tk:.1f} \\\\")
            out.append(r"\enddata")
            out.append(r"\end{deluxetable}")
        out.append("")

    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT} ({n_written} source appendices)")


if __name__ == "__main__":
    main()
